ktor:
  application:
    modules:
      - com.codingcanines.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  secret: $JWT_SECRET
  issuer: "https://0.0.0.0:8433"
  audience: "gameplanner"
  realm: "Access to Game Planner API"
